
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_ERRORS = 'AUTH_ERRORS';
export const LOG_OUT = 'LOG_OUT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';